services:
  bot:
    build: ./
    image: syabejiro
    volumes:
     - ./.env:/usr/src/app/.env
     - ./wordbook.json:/usr/src/app/wordbook.json
     - ./cache:/usr/src/app/cache
    restart: always